// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: internal/selflow-runner-proto/sfrunner.proto

package selflow_runner_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRunner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitRunner) Reset() {
	*x = InitRunner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRunner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRunner) ProtoMessage() {}

func (x *InitRunner) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRunner.ProtoReflect.Descriptor instead.
func (*InitRunner) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{0}
}

type SpawnContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawnContainer) Reset() {
	*x = SpawnContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnContainer) ProtoMessage() {}

func (x *SpawnContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnContainer.ProtoReflect.Descriptor instead.
func (*SpawnContainer) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{1}
}

type InitRunner_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerSpawnServer uint32 `protobuf:"varint,1,opt,name=containerSpawnServer,proto3" json:"containerSpawnServer,omitempty"`
}

func (x *InitRunner_Request) Reset() {
	*x = InitRunner_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRunner_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRunner_Request) ProtoMessage() {}

func (x *InitRunner_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRunner_Request.ProtoReflect.Descriptor instead.
func (*InitRunner_Request) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InitRunner_Request) GetContainerSpawnServer() uint32 {
	if x != nil {
		return x.ContainerSpawnServer
	}
	return 0
}

type InitRunner_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitRunner_Response) Reset() {
	*x = InitRunner_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRunner_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRunner_Response) ProtoMessage() {}

func (x *InitRunner_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRunner_Response.ProtoReflect.Descriptor instead.
func (*InitRunner_Response) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{0, 1}
}

type SpawnContainer_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string            `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Environment map[string]string `protobuf:"bytes,2,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cmd         string            `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Image       string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *SpawnContainer_Request) Reset() {
	*x = SpawnContainer_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnContainer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnContainer_Request) ProtoMessage() {}

func (x *SpawnContainer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnContainer_Request.ProtoReflect.Descriptor instead.
func (*SpawnContainer_Request) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SpawnContainer_Request) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SpawnContainer_Request) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *SpawnContainer_Request) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *SpawnContainer_Request) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type SpawnContainer_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawnContainer_Response) Reset() {
	*x = SpawnContainer_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnContainer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnContainer_Response) ProtoMessage() {}

func (x *SpawnContainer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnContainer_Response.ProtoReflect.Descriptor instead.
func (*SpawnContainer_Response) Descriptor() ([]byte, []int) {
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP(), []int{1, 1}
}

var File_internal_selflow_runner_proto_sfrunner_proto protoreflect.FileDescriptor

var file_internal_selflow_runner_proto_sfrunner_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c,
	0x6f, 0x77, 0x2d, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x66, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x1a, 0x3d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x14, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x93, 0x02,
	0x0a, 0x0e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x1a, 0xf4, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x5f,
	0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x3e, 0x0a, 0x10, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x81, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x6d, 0x0a, 0x0e, 0x53, 0x70, 0x61, 0x77,
	0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x2c, 0x2e, 0x73, 0x65, 0x6c,
	0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x6c,
	0x6f, 0x77, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x72, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x66, 0x6c,
	0x6f, 0x77, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77,
	0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_selflow_runner_proto_sfrunner_proto_rawDescOnce sync.Once
	file_internal_selflow_runner_proto_sfrunner_proto_rawDescData = file_internal_selflow_runner_proto_sfrunner_proto_rawDesc
)

func file_internal_selflow_runner_proto_sfrunner_proto_rawDescGZIP() []byte {
	file_internal_selflow_runner_proto_sfrunner_proto_rawDescOnce.Do(func() {
		file_internal_selflow_runner_proto_sfrunner_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_selflow_runner_proto_sfrunner_proto_rawDescData)
	})
	return file_internal_selflow_runner_proto_sfrunner_proto_rawDescData
}

var file_internal_selflow_runner_proto_sfrunner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_selflow_runner_proto_sfrunner_proto_goTypes = []interface{}{
	(*InitRunner)(nil),              // 0: selflow_runner_proto.InitRunner
	(*SpawnContainer)(nil),          // 1: selflow_runner_proto.SpawnContainer
	(*InitRunner_Request)(nil),      // 2: selflow_runner_proto.InitRunner.Request
	(*InitRunner_Response)(nil),     // 3: selflow_runner_proto.InitRunner.Response
	(*SpawnContainer_Request)(nil),  // 4: selflow_runner_proto.SpawnContainer.Request
	(*SpawnContainer_Response)(nil), // 5: selflow_runner_proto.SpawnContainer.Response
	nil,                             // 6: selflow_runner_proto.SpawnContainer.Request.EnvironmentEntry
}
var file_internal_selflow_runner_proto_sfrunner_proto_depIdxs = []int32{
	6, // 0: selflow_runner_proto.SpawnContainer.Request.environment:type_name -> selflow_runner_proto.SpawnContainer.Request.EnvironmentEntry
	4, // 1: selflow_runner_proto.ContainerSpawner.SpawnContainer:input_type -> selflow_runner_proto.SpawnContainer.Request
	2, // 2: selflow_runner_proto.SelflowRunner.InitRunner:input_type -> selflow_runner_proto.InitRunner.Request
	5, // 3: selflow_runner_proto.ContainerSpawner.SpawnContainer:output_type -> selflow_runner_proto.SpawnContainer.Response
	3, // 4: selflow_runner_proto.SelflowRunner.InitRunner:output_type -> selflow_runner_proto.InitRunner.Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_selflow_runner_proto_sfrunner_proto_init() }
func file_internal_selflow_runner_proto_sfrunner_proto_init() {
	if File_internal_selflow_runner_proto_sfrunner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRunner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRunner_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRunner_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnContainer_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_selflow_runner_proto_sfrunner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnContainer_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_selflow_runner_proto_sfrunner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_selflow_runner_proto_sfrunner_proto_goTypes,
		DependencyIndexes: file_internal_selflow_runner_proto_sfrunner_proto_depIdxs,
		MessageInfos:      file_internal_selflow_runner_proto_sfrunner_proto_msgTypes,
	}.Build()
	File_internal_selflow_runner_proto_sfrunner_proto = out.File
	file_internal_selflow_runner_proto_sfrunner_proto_rawDesc = nil
	file_internal_selflow_runner_proto_sfrunner_proto_goTypes = nil
	file_internal_selflow_runner_proto_sfrunner_proto_depIdxs = nil
}
