// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: cmd/selflow-daemon/server/proto/daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticType int32

const (
	DiagnosticType_ERROR   DiagnosticType = 0
	DiagnosticType_WARNING DiagnosticType = 1
	DiagnosticType_INFO    DiagnosticType = 2
	DiagnosticType_DEBUG   DiagnosticType = 3
)

// Enum value maps for DiagnosticType.
var (
	DiagnosticType_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
		3: "DEBUG",
	}
	DiagnosticType_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
		"DEBUG":   3,
	}
)

func (x DiagnosticType) Enum() *DiagnosticType {
	p := new(DiagnosticType)
	*p = x
	return p
}

func (x DiagnosticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (DiagnosticType) Type() protoreflect.EnumType {
	return &file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes[0]
}

func (x DiagnosticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticType.Descriptor instead.
func (DiagnosticType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{0}
}

type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DiagnosticType `protobuf:"varint,1,opt,name=type,proto3,enum=DiagnosticType" json:"type,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *Diagnostic) GetType() DiagnosticType {
	if x != nil {
		return x.Type
	}
	return DiagnosticType_ERROR
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1}
}

type StartRun_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunConfig []byte `protobuf:"bytes,1,opt,name=runConfig,proto3" json:"runConfig,omitempty"`
}

func (x *StartRun_Request) Reset() {
	*x = StartRun_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Request) ProtoMessage() {}

func (x *StartRun_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Request.ProtoReflect.Descriptor instead.
func (*StartRun_Request) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StartRun_Request) GetRunConfig() []byte {
	if x != nil {
		return x.RunConfig
	}
	return nil
}

type StartRun_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RunId       string        `protobuf:"bytes,2,opt,name=runId,proto3" json:"runId,omitempty"`
}

func (x *StartRun_Response) Reset() {
	*x = StartRun_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Response) ProtoMessage() {}

func (x *StartRun_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Response.ProtoReflect.Descriptor instead.
func (*StartRun_Response) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1, 1}
}

func (x *StartRun_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *StartRun_Response) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_cmd_selflow_daemon_server_proto_daemon_proto protoreflect.FileDescriptor

var file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x08,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x1a, 0x27, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x4f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x75, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6e,
	0x49, 0x64, 0x2a, 0x3d, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10,
	0x03, 0x32, 0x3b, 0x0a, 0x06, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x11, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21,
	0x5a, 0x1f, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescOnce sync.Once
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData = file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc
)

func file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP() []byte {
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescOnce.Do(func() {
		file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData)
	})
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData
}

var file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes = []interface{}{
	(DiagnosticType)(0),       // 0: DiagnosticType
	(*Diagnostic)(nil),        // 1: Diagnostic
	(*StartRun)(nil),          // 2: StartRun
	(*StartRun_Request)(nil),  // 3: StartRun.Request
	(*StartRun_Response)(nil), // 4: StartRun.Response
}
var file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs = []int32{
	0, // 0: Diagnostic.type:type_name -> DiagnosticType
	1, // 1: StartRun.Response.diagnostics:type_name -> Diagnostic
	3, // 2: Daemon.StartRun:input_type -> StartRun.Request
	4, // 3: Daemon.StartRun:output_type -> StartRun.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_selflow_daemon_server_proto_daemon_proto_init() }
func file_cmd_selflow_daemon_server_proto_daemon_proto_init() {
	if File_cmd_selflow_daemon_server_proto_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes,
		DependencyIndexes: file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs,
		EnumInfos:         file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes,
		MessageInfos:      file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes,
	}.Build()
	File_cmd_selflow_daemon_server_proto_daemon_proto = out.File
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc = nil
	file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes = nil
	file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs = nil
}
