// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: cmd/selflow-daemon/server/proto/daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticType int32

const (
	DiagnosticType_ERROR   DiagnosticType = 0
	DiagnosticType_WARNING DiagnosticType = 1
	DiagnosticType_INFO    DiagnosticType = 2
	DiagnosticType_DEBUG   DiagnosticType = 3
)

// Enum value maps for DiagnosticType.
var (
	DiagnosticType_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
		3: "DEBUG",
	}
	DiagnosticType_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
		"DEBUG":   3,
	}
)

func (x DiagnosticType) Enum() *DiagnosticType {
	p := new(DiagnosticType)
	*p = x
	return p
}

func (x DiagnosticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (DiagnosticType) Type() protoreflect.EnumType {
	return &file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes[0]
}

func (x DiagnosticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticType.Descriptor instead.
func (DiagnosticType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{0}
}

type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DiagnosticType `protobuf:"varint,1,opt,name=type,proto3,enum=DiagnosticType" json:"type,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *Diagnostic) GetType() DiagnosticType {
	if x != nil {
		return x.Type
	}
	return DiagnosticType_ERROR
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1}
}

type GetLogStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLogStream) Reset() {
	*x = GetLogStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogStream) ProtoMessage() {}

func (x *GetLogStream) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogStream.ProtoReflect.Descriptor instead.
func (*GetLogStream) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{2}
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level    string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	DateTime string `protobuf:"bytes,2,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRunStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRunStatus) Reset() {
	*x = GetRunStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStatus) ProtoMessage() {}

func (x *GetRunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStatus.ProtoReflect.Descriptor instead.
func (*GetRunStatus) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{4}
}

type StartRun_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunConfig []byte `protobuf:"bytes,1,opt,name=runConfig,proto3" json:"runConfig,omitempty"`
}

func (x *StartRun_Request) Reset() {
	*x = StartRun_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Request) ProtoMessage() {}

func (x *StartRun_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Request.ProtoReflect.Descriptor instead.
func (*StartRun_Request) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StartRun_Request) GetRunConfig() []byte {
	if x != nil {
		return x.RunConfig
	}
	return nil
}

type StartRun_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RunId       string        `protobuf:"bytes,2,opt,name=runId,proto3" json:"runId,omitempty"`
}

func (x *StartRun_Response) Reset() {
	*x = StartRun_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRun_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Response) ProtoMessage() {}

func (x *StartRun_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Response.ProtoReflect.Descriptor instead.
func (*StartRun_Response) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{1, 1}
}

func (x *StartRun_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *StartRun_Response) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetLogStream_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=runId,proto3" json:"runId,omitempty"`
}

func (x *GetLogStream_Request) Reset() {
	*x = GetLogStream_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogStream_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogStream_Request) ProtoMessage() {}

func (x *GetLogStream_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogStream_Request.ProtoReflect.Descriptor instead.
func (*GetLogStream_Request) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetLogStream_Request) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunStatus_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=runId,proto3" json:"runId,omitempty"`
}

func (x *GetRunStatus_Request) Reset() {
	*x = GetRunStatus_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunStatus_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStatus_Request) ProtoMessage() {}

func (x *GetRunStatus_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStatus_Request.ProtoReflect.Descriptor instead.
func (*GetRunStatus_Request) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetRunStatus_Request) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunStatus_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	IsFinished    bool   `protobuf:"varint,3,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	IsCancellable bool   `protobuf:"varint,4,opt,name=isCancellable,proto3" json:"isCancellable,omitempty"`
}

func (x *GetRunStatus_Status) Reset() {
	*x = GetRunStatus_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunStatus_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStatus_Status) ProtoMessage() {}

func (x *GetRunStatus_Status) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStatus_Status.ProtoReflect.Descriptor instead.
func (*GetRunStatus_Status) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetRunStatus_Status) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRunStatus_Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRunStatus_Status) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *GetRunStatus_Status) GetIsCancellable() bool {
	if x != nil {
		return x.IsCancellable
	}
	return false
}

type GetRunStatus_Dependence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dependencies []string `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *GetRunStatus_Dependence) Reset() {
	*x = GetRunStatus_Dependence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunStatus_Dependence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStatus_Dependence) ProtoMessage() {}

func (x *GetRunStatus_Dependence) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStatus_Dependence.ProtoReflect.Descriptor instead.
func (*GetRunStatus_Dependence) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{4, 2}
}

func (x *GetRunStatus_Dependence) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type GetRunStatus_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State        map[string]*GetRunStatus_Status     `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Dependencies map[string]*GetRunStatus_Dependence `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetRunStatus_Response) Reset() {
	*x = GetRunStatus_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunStatus_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStatus_Response) ProtoMessage() {}

func (x *GetRunStatus_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStatus_Response.ProtoReflect.Descriptor instead.
func (*GetRunStatus_Response) Descriptor() ([]byte, []int) {
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP(), []int{4, 3}
}

func (x *GetRunStatus_Response) GetState() map[string]*GetRunStatus_Status {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetRunStatus_Response) GetDependencies() map[string]*GetRunStatus_Dependence {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_cmd_selflow_daemon_server_proto_daemon_proto protoreflect.FileDescriptor

var file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x08,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x1a, 0x27, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x4f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x75, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6e,
	0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x1a, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75,
	0x6e, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x98, 0x04, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x1f, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x1a, 0x76, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x69, 0x73, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x1a, 0x30, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x1a, 0xbc, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x0c,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x1a, 0x4e, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x59, 0x0a, 0x11, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x3d, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42,
	0x55, 0x47, 0x10, 0x03, 0x32, 0xa9, 0x01, 0x0a, 0x06, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12,
	0x31, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x11, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x04, 0x2e, 0x4c, 0x6f, 0x67, 0x30,
	0x01, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x21, 0x5a, 0x1f, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescOnce sync.Once
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData = file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc
)

func file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescGZIP() []byte {
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescOnce.Do(func() {
		file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData)
	})
	return file_cmd_selflow_daemon_server_proto_daemon_proto_rawDescData
}

var file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes = []interface{}{
	(DiagnosticType)(0),             // 0: DiagnosticType
	(*Diagnostic)(nil),              // 1: Diagnostic
	(*StartRun)(nil),                // 2: StartRun
	(*GetLogStream)(nil),            // 3: GetLogStream
	(*Log)(nil),                     // 4: Log
	(*GetRunStatus)(nil),            // 5: GetRunStatus
	(*StartRun_Request)(nil),        // 6: StartRun.Request
	(*StartRun_Response)(nil),       // 7: StartRun.Response
	(*GetLogStream_Request)(nil),    // 8: GetLogStream.Request
	(*GetRunStatus_Request)(nil),    // 9: GetRunStatus.Request
	(*GetRunStatus_Status)(nil),     // 10: GetRunStatus.Status
	(*GetRunStatus_Dependence)(nil), // 11: GetRunStatus.Dependence
	(*GetRunStatus_Response)(nil),   // 12: GetRunStatus.Response
	nil,                             // 13: GetRunStatus.Response.StateEntry
	nil,                             // 14: GetRunStatus.Response.DependenciesEntry
}
var file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs = []int32{
	0,  // 0: Diagnostic.type:type_name -> DiagnosticType
	1,  // 1: StartRun.Response.diagnostics:type_name -> Diagnostic
	13, // 2: GetRunStatus.Response.state:type_name -> GetRunStatus.Response.StateEntry
	14, // 3: GetRunStatus.Response.dependencies:type_name -> GetRunStatus.Response.DependenciesEntry
	10, // 4: GetRunStatus.Response.StateEntry.value:type_name -> GetRunStatus.Status
	11, // 5: GetRunStatus.Response.DependenciesEntry.value:type_name -> GetRunStatus.Dependence
	6,  // 6: Daemon.StartRun:input_type -> StartRun.Request
	8,  // 7: Daemon.GetLogStream:input_type -> GetLogStream.Request
	9,  // 8: Daemon.GetRunStatus:input_type -> GetRunStatus.Request
	7,  // 9: Daemon.StartRun:output_type -> StartRun.Response
	4,  // 10: Daemon.GetLogStream:output_type -> Log
	12, // 11: Daemon.GetRunStatus:output_type -> GetRunStatus.Response
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cmd_selflow_daemon_server_proto_daemon_proto_init() }
func file_cmd_selflow_daemon_server_proto_daemon_proto_init() {
	if File_cmd_selflow_daemon_server_proto_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRun_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogStream_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunStatus_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunStatus_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunStatus_Dependence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunStatus_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes,
		DependencyIndexes: file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs,
		EnumInfos:         file_cmd_selflow_daemon_server_proto_daemon_proto_enumTypes,
		MessageInfos:      file_cmd_selflow_daemon_server_proto_daemon_proto_msgTypes,
	}.Build()
	File_cmd_selflow_daemon_server_proto_daemon_proto = out.File
	file_cmd_selflow_daemon_server_proto_daemon_proto_rawDesc = nil
	file_cmd_selflow_daemon_server_proto_daemon_proto_goTypes = nil
	file_cmd_selflow_daemon_server_proto_daemon_proto_depIdxs = nil
}
