// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: docs/selflow-plugin-protocol/sfplugin-0.1.proto

package selflow_plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginType int32

const (
	PluginType_INITIATOR PluginType = 0
	PluginType_ARCHITECT PluginType = 1
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "INITIATOR",
		1: "ARCHITECT",
	}
	PluginType_value = map[string]int32{
		"INITIATOR": 0,
		"ARCHITECT": 1,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{0}
}

type DiagnosticType int32

const (
	DiagnosticType_ERROR   DiagnosticType = 0
	DiagnosticType_WARNING DiagnosticType = 1
	DiagnosticType_INFO    DiagnosticType = 2
	DiagnosticType_DEBUG   DiagnosticType = 3
)

// Enum value maps for DiagnosticType.
var (
	DiagnosticType_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
		3: "DEBUG",
	}
	DiagnosticType_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
		"DEBUG":   3,
	}
)

func (x DiagnosticType) Enum() *DiagnosticType {
	p := new(DiagnosticType)
	*p = x
	return p
}

func (x DiagnosticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticType) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes[1].Descriptor()
}

func (DiagnosticType) Type() protoreflect.EnumType {
	return &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes[1]
}

func (x DiagnosticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticType.Descriptor instead.
func (DiagnosticType) EnumDescriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{1}
}

type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DiagnosticType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.DiagnosticType" json:"type,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{0}
}

func (x *Diagnostic) GetType() DiagnosticType {
	if x != nil {
		return x.Type
	}
	return DiagnosticType_ERROR
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type of the schema (ex: string, number, boolean, object, list, map), leaved as black to allow sur-typing without
	// re-writing the proto configuration for example with selects, long strings, integer...
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// If the type is complex (ex: list, object), nested children types
	NestedGroups []*Schema `protobuf:"bytes,2,rep,name=nestedGroups,proto3" json:"nestedGroups,omitempty"`
	// description of the schema
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// if true, the field must be required to validate the schema
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// if true the field will be marked as deprecated
	Deprecated bool `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Schema) GetNestedGroups() []*Schema {
	if x != nil {
		return x.NestedGroups
	}
	return nil
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Schema) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

type GetPluginSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginSchema) Reset() {
	*x = GetPluginSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginSchema) ProtoMessage() {}

func (x *GetPluginSchema) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginSchema.ProtoReflect.Descriptor instead.
func (*GetPluginSchema) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{2}
}

type ValidatePluginConfigSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidatePluginConfigSchema) Reset() {
	*x = ValidatePluginConfigSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePluginConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePluginConfigSchema) ProtoMessage() {}

func (x *ValidatePluginConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePluginConfigSchema.ProtoReflect.Descriptor instead.
func (*ValidatePluginConfigSchema) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{3}
}

type ValidateStepConfigSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidateStepConfigSchema) Reset() {
	*x = ValidateStepConfigSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateStepConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStepConfigSchema) ProtoMessage() {}

func (x *ValidateStepConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStepConfigSchema.ProtoReflect.Descriptor instead.
func (*ValidateStepConfigSchema) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{4}
}

type RunStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunStep) Reset() {
	*x = RunStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStep) ProtoMessage() {}

func (x *RunStep) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStep.ProtoReflect.Descriptor instead.
func (*RunStep) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{5}
}

type GetPluginSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginSchema_Request) Reset() {
	*x = GetPluginSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginSchema_Request) ProtoMessage() {}

func (x *GetPluginSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginSchema_Request.ProtoReflect.Descriptor instead.
func (*GetPluginSchema_Request) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{2, 0}
}

type GetPluginSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of plugin types that the plugin supports
	PluginTypes []PluginType `protobuf:"varint,1,rep,packed,name=pluginTypes,proto3,enum=proto.PluginType" json:"pluginTypes,omitempty"`
	// List of step schemas that the plugin support
	StepSchemas map[string]*Schema `protobuf:"bytes,2,rep,name=stepSchemas,proto3" json:"stepSchemas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetPluginSchema_Response) Reset() {
	*x = GetPluginSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginSchema_Response) ProtoMessage() {}

func (x *GetPluginSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginSchema_Response.ProtoReflect.Descriptor instead.
func (*GetPluginSchema_Response) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetPluginSchema_Response) GetPluginTypes() []PluginType {
	if x != nil {
		return x.PluginTypes
	}
	return nil
}

func (x *GetPluginSchema_Response) GetStepSchemas() map[string]*Schema {
	if x != nil {
		return x.StepSchemas
	}
	return nil
}

type ValidatePluginConfigSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginConfig []byte `protobuf:"bytes,1,opt,name=pluginConfig,proto3" json:"pluginConfig,omitempty"`
}

func (x *ValidatePluginConfigSchema_Request) Reset() {
	*x = ValidatePluginConfigSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePluginConfigSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePluginConfigSchema_Request) ProtoMessage() {}

func (x *ValidatePluginConfigSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePluginConfigSchema_Request.ProtoReflect.Descriptor instead.
func (*ValidatePluginConfigSchema_Request) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ValidatePluginConfigSchema_Request) GetPluginConfig() []byte {
	if x != nil {
		return x.PluginConfig
	}
	return nil
}

type ValidatePluginConfigSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid      bool          `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Diagnotics []*Diagnostic `protobuf:"bytes,2,rep,name=diagnotics,proto3" json:"diagnotics,omitempty"`
}

func (x *ValidatePluginConfigSchema_Response) Reset() {
	*x = ValidatePluginConfigSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePluginConfigSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePluginConfigSchema_Response) ProtoMessage() {}

func (x *ValidatePluginConfigSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePluginConfigSchema_Response.ProtoReflect.Descriptor instead.
func (*ValidatePluginConfigSchema_Response) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ValidatePluginConfigSchema_Response) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePluginConfigSchema_Response) GetDiagnotics() []*Diagnostic {
	if x != nil {
		return x.Diagnotics
	}
	return nil
}

type ValidateStepConfigSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepName   string `protobuf:"bytes,1,opt,name=stepName,proto3" json:"stepName,omitempty"`
	StepConfig []byte `protobuf:"bytes,2,opt,name=stepConfig,proto3" json:"stepConfig,omitempty"`
}

func (x *ValidateStepConfigSchema_Request) Reset() {
	*x = ValidateStepConfigSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateStepConfigSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStepConfigSchema_Request) ProtoMessage() {}

func (x *ValidateStepConfigSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStepConfigSchema_Request.ProtoReflect.Descriptor instead.
func (*ValidateStepConfigSchema_Request) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ValidateStepConfigSchema_Request) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ValidateStepConfigSchema_Request) GetStepConfig() []byte {
	if x != nil {
		return x.StepConfig
	}
	return nil
}

type ValidateStepConfigSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid      bool          `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Diagnotics []*Diagnostic `protobuf:"bytes,2,rep,name=diagnotics,proto3" json:"diagnotics,omitempty"`
}

func (x *ValidateStepConfigSchema_Response) Reset() {
	*x = ValidateStepConfigSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateStepConfigSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStepConfigSchema_Response) ProtoMessage() {}

func (x *ValidateStepConfigSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStepConfigSchema_Response.ProtoReflect.Descriptor instead.
func (*ValidateStepConfigSchema_Response) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ValidateStepConfigSchema_Response) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateStepConfigSchema_Response) GetDiagnotics() []*Diagnostic {
	if x != nil {
		return x.Diagnotics
	}
	return nil
}

type RunStep_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepName   string `protobuf:"bytes,1,opt,name=stepName,proto3" json:"stepName,omitempty"`
	StepConfig []byte `protobuf:"bytes,2,opt,name=stepConfig,proto3" json:"stepConfig,omitempty"`
}

func (x *RunStep_Request) Reset() {
	*x = RunStep_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunStep_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStep_Request) ProtoMessage() {}

func (x *RunStep_Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStep_Request.ProtoReflect.Descriptor instead.
func (*RunStep_Request) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RunStep_Request) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *RunStep_Request) GetStepConfig() []byte {
	if x != nil {
		return x.StepConfig
	}
	return nil
}

type RunStep_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunStep_Response) Reset() {
	*x = RunStep_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunStep_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStep_Response) ProtoMessage() {}

func (x *RunStep_Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStep_Response.ProtoReflect.Descriptor instead.
func (*RunStep_Response) Descriptor() ([]byte, []int) {
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP(), []int{5, 1}
}

var File_docs_selflow_plugin_protocol_sfplugin_0_1_proto protoreflect.FileDescriptor

var file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73,
	0x66, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x30, 0x2e, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x06,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x6e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x0c, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x22, 0x81, 0x02, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xe2, 0x01, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x0b,
	0x73, 0x74, 0x65, 0x70, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0b, 0x73, 0x74, 0x65, 0x70, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73,
	0x1a, 0x4d, 0x0a, 0x10, 0x53, 0x74, 0x65, 0x70, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xa0, 0x01, 0x0a, 0x1a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x2d,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x53, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x31, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x74, 0x69,
	0x63, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x65, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x74, 0x65, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x53, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x0a, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x22, 0x5c, 0x0a, 0x07, 0x52,
	0x75, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x1a, 0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x73, 0x74, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x2a, 0x0a, 0x0a, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49,
	0x41, 0x54, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x52, 0x43, 0x48, 0x49, 0x54,
	0x45, 0x43, 0x54, 0x10, 0x01, 0x2a, 0x3d, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42,
	0x55, 0x47, 0x10, 0x03, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x6c, 0x66,
	0x6c, 0x6f, 0x77, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescOnce sync.Once
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescData = file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDesc
)

func file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescGZIP() []byte {
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescOnce.Do(func() {
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescData)
	})
	return file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDescData
}

var file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_goTypes = []interface{}{
	(PluginType)(0),                             // 0: proto.PluginType
	(DiagnosticType)(0),                         // 1: proto.DiagnosticType
	(*Diagnostic)(nil),                          // 2: proto.Diagnostic
	(*Schema)(nil),                              // 3: proto.Schema
	(*GetPluginSchema)(nil),                     // 4: proto.GetPluginSchema
	(*ValidatePluginConfigSchema)(nil),          // 5: proto.ValidatePluginConfigSchema
	(*ValidateStepConfigSchema)(nil),            // 6: proto.ValidateStepConfigSchema
	(*RunStep)(nil),                             // 7: proto.RunStep
	(*GetPluginSchema_Request)(nil),             // 8: proto.GetPluginSchema.Request
	(*GetPluginSchema_Response)(nil),            // 9: proto.GetPluginSchema.Response
	nil,                                         // 10: proto.GetPluginSchema.Response.StepSchemasEntry
	(*ValidatePluginConfigSchema_Request)(nil),  // 11: proto.ValidatePluginConfigSchema.Request
	(*ValidatePluginConfigSchema_Response)(nil), // 12: proto.ValidatePluginConfigSchema.Response
	(*ValidateStepConfigSchema_Request)(nil),    // 13: proto.ValidateStepConfigSchema.Request
	(*ValidateStepConfigSchema_Response)(nil),   // 14: proto.ValidateStepConfigSchema.Response
	(*RunStep_Request)(nil),                     // 15: proto.RunStep.Request
	(*RunStep_Response)(nil),                    // 16: proto.RunStep.Response
}
var file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_depIdxs = []int32{
	1,  // 0: proto.Diagnostic.type:type_name -> proto.DiagnosticType
	3,  // 1: proto.Schema.nestedGroups:type_name -> proto.Schema
	0,  // 2: proto.GetPluginSchema.Response.pluginTypes:type_name -> proto.PluginType
	10, // 3: proto.GetPluginSchema.Response.stepSchemas:type_name -> proto.GetPluginSchema.Response.StepSchemasEntry
	3,  // 4: proto.GetPluginSchema.Response.StepSchemasEntry.value:type_name -> proto.Schema
	2,  // 5: proto.ValidatePluginConfigSchema.Response.diagnotics:type_name -> proto.Diagnostic
	2,  // 6: proto.ValidateStepConfigSchema.Response.diagnotics:type_name -> proto.Diagnostic
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_init() }
func file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_init() {
	if File_docs_selflow_plugin_protocol_sfplugin_0_1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePluginConfigSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateStepConfigSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePluginConfigSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePluginConfigSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateStepConfigSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateStepConfigSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunStep_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunStep_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_goTypes,
		DependencyIndexes: file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_depIdxs,
		EnumInfos:         file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_enumTypes,
		MessageInfos:      file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_msgTypes,
	}.Build()
	File_docs_selflow_plugin_protocol_sfplugin_0_1_proto = out.File
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_rawDesc = nil
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_goTypes = nil
	file_docs_selflow_plugin_protocol_sfplugin_0_1_proto_depIdxs = nil
}
