name: Commit Linter
on: [pull_request]

env:
  GITMOJI_URL: https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn
      - name: Install gitmoji json
        run: wget -O ./node_modules/commitlint-plugin-gitmoji/lib/gitmojis.json "$GITMOJI_URL"
      - uses: wagoid/commitlint-github-action@v5
