name: Documentation publish
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn

      - run: npx nx build selflow-documentation --skip-nx-cache

      - name: Publish to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/apps/selflow-documentation
