name: NX CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  CGO_ENABLED: 1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install yarn
        run: npm install -g yarn

      - uses: nrwl/nx-set-shas@v2
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - run: yarn nx workspace-lint
      - run: yarn nx affected --target=test --parallel=3
      - run: mkdir tmp
      - run: SELFLOW_DAEMON_HOST_BASED_DIRECTORY="$PWD/tmp" yarn nx affected --target=e2e --parallel=3
      - run: yarn nx format:check
      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=build --parallel=3
