name: NX CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    with:
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=test --parallel=3
        npx nx affected --target=e2e --parallel=3
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=build --parallel=3
      init-commands: |
        wget https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
        rm -rf ./go && tar -C ./go -xzf go1.21.3.linux-amd64.tar.gz
        echo ::add-path $PWD/go

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
